name: CI

on:
  - push
  - workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_id: ["0", "1", "2", "3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: sbt test
        env:
          MATRIX_TEST_ID: "${{ matrix.test_id }}"
          MATRIX_SIZE: 4 # Be careful to sync with matrix.test_id above.
        run: sbt test
      - name: Cleanup before cache
        shell: bash
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
